### PR TITLE
Reporting view created to display basic info of each event

### PR DESCRIPTION
**Pull request by jeezOC**
image

### CODE REVIEW

**Comment by joshmg-77** [comment]
Hey Good job, I just have a concern and it's about UI specifically on the overflow for the **total collected**, my humble suggestion is the following
React App 2023-01-31 09-56-47

I don't know if that's correct or if that is as expected.

example: 
[Returnjsx.txt](https://github.com/hermosasoftware/ticket-manager/files/10548297/Returnjsx.txt)

**Comment by jeezOC** [comment]
Thanks, that looks so much better, I suggest maybe align the label in question to the right, but anyways thanks Josh, feel free to push those changes in the same branch

**Comment by joshmg-77** [comment]
> Thanks, that looks so much better, I suggest maybe align the label in question to the right, but anyways thanks Josh, feel free to push those changes in the same branch

Awesome Ale, I'll do!!

**Review by joshmg-77 — APPROVED** [review]
Ready to be merged 🚀

**Pull request merged**
